export const CONSTANTS = {
    CUSTOMER_TOKEN: 'V_CUSTOMER_TOKEN',
    CURRENT_CUSTOMIZATION: 'V_CURRENT_CUSTOMIZATION_ID',
    CURRENT_PRODUCT: 'V_CURRENT_PRODUCT_ID',
    PREVIOUS_CATEGORY: 'V_PREVIOUS_CATEGORY_ID',
    V_ORDER: 'V_ORDER_ID',
    JAR_LIMITS: 99,
    PROP_HISTORY: 'PROP_HISTORY'
}
